name: Nix Seed Build
description: Builder for Nix Seed

inputs:

  seed:
    description: Seed name
    default: ghcr.io/${{ github.repository }}.seed
  tag:
    description: Seed tag
    default: latest
  target:
    description: Target flake attribute
    default: packages.default

  github_token:
    description: GitHub Token
  tags:
    description: Extra tags (space-separated)

  cachix_name:
    description: Cachix cache name
    default: ${{ github.event.repository.name }}
  cachix_auth_token:
    description: Cachix auth token
  cachix_signing_key:
    description: Cachix signing key

runs:
  using: composite
  steps:
    - shell: bash
      run: ./ci/build-from-seed
