name: Nix Seed
description: Build and push Nix Seed environments to GHCR

inputs:

  nix_conf:
    description: Extra nix.conf entries

  seed_attr:
    description: Flake package attribute of the build seed
    default: .#seed

  registry:
    description: Container registry (default ghcr.io)
    default: ghcr.io
  registry_token:
    description: Hub Token for registry login
  tags:
    description: Extra tags (space-separated)

  cachix_name:
    description: Cachix cache name
    default: ${{ github.event.repository.name }}
  cachix_auth_token:
    description: Cachix auth token
  cachix_signing_key:
    description: Cachix signing key

runs:
  using: composite
  steps:
    - name: Nix Setup
      uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          ${{ inputs.nix_conf }}

    - name: Cachix Setup
      if: ${{ inputs.cachix_token != '' }}
      uses: cachix/cachix-action@v16
      with:
        name: ${{ inputs.cachix_name }}
        authToken: ${{ inputs.cachix_auth_token }}
        signingKey: ${{ inputs.cachix_signing_key }}

    - name: Build seed
      shell: bash
      run: nix build "${{ inputs.seed_attr }}"

    - name: GHCR Publish
      if: ${{ inputs.registry_token != '' }}
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_TOKEN: ${{ inputs.registry_token }}
        # enable keyless signing so sign-in uses existing runner credentials rather than device flow
        COSIGN_EXPERIMENTAL: "1"
      shell: bash
      run: |-
        set -euo pipefail
        tags=()
        if [[ -n "${{ inputs.tags }}" ]]; then
          read -ra parsed_tags <<< "${{ inputs.tags }}"
          for tag in "${parsed_tags[@]}"; do
            tags+=(--tag "$tag")
          done
        fi
        nix run .#publish -- "${tags[@]}" ${{ inputs.registry }}/${{ github.repository }} ${{ github.sha }}
