#!/usr/bin/env bash

set -euo pipefail

echo "::group::Verify Seed Integrity"
echo "::group::Install Skopeo"
sudo apt-get update
sudo apt-get install -y skopeo
echo ::endgroup::
digest=$(
  skopeo inspect \
    --creds="${{ github.actor }}:${{ inputs.github_token }}" \
    docker://${{ inputs.seed }}:${{ inputs.tag }} |
    jq -r .Digest
)
echo "::notice::Digest: $digest"
echo ::endgroup::


echo "::group::Pull Seed"
docker pull ${{ seed }}@$digest
echo ::endgroup::

echo "::group::Build"
docker run \
  --network none \
  --tmpfs /tmp \
  --volume ${{ github.workspace }}:/build \
  ghcr.io/${{ github.repository }}:${{ github.sha }} \
  nix build --print-build-logs /build#${{ inputs.target }}
echo ::endgroup::
